variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: mstrasuns/ubuntu-dlang:2.081

stages:
  - test

unittest:
  stage: test
  script:
    - dub test

samples:
  stage: test
  script:
    - ci/test-samples.sh

expected-compiles:
  stage: test
  script:
    - ci/test-expected.sh
