jobs:
  - job: Sanity
    pool:
      vmImage: 'ubuntu 16.04'
    steps:
      - bash: ./ci/test-expected.sh
        displayName: Check that expected headers compile

  - job: Linux
    variables:
      url: https://github.com/ldc-developers/ldc/releases/download/v1.13.0/ldc2-1.13.0-linux-x86_64.tar.xz
      bindir: ldc/ldc2-1.13.0-linux-x86_64/bin
      archive: ldc.tar.xz
    pool:
      vmImage: 'ubuntu 16.04'
    steps:
      - template: build-template.yml

  - job: Windows
    variables:
      url: https://github.com/ldc-developers/ldc/releases/download/v1.13.0/ldc2-1.13.0-windows-multilib.7z
      bindir: ldc/ldc2-1.13.0-windows-multilib/bin
      archive: ldc.7z
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: build-template.yml
