jobs:
  - job: Sanity
    pool:
      vmImage: 'ubuntu 16.04'
    steps:
      - bash: ./ci/test-expected.sh
        displayName: Check that expected headers compile

  - job: Linux
    variables:
      url: https://github.com/mihails-strasuns/dc/releases/download/v0.1.0/dc
    pool:
      vmImage: 'ubuntu 16.04'
    steps:
      - template: build-template.yml

  - job: Windows
    variables:
      url: https://github.com/mihails-strasuns/dc/releases/download/v0.1.0/dc.exe
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: build-template.yml
